<?php

namespace ContainerQKDSyHe;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8_gton2.App\Controller\UserController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8_gton2.App\\Controller\\UserController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'employeRepository' => ['privates', '.errored.TRNxvrL', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::index()": the $employeRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\EmployeRepository".'],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'employeRepository' => '?',
        ]))->withContext('App\\Controller\\UserController::index()', $container);
    }
}
