<?php

namespace ContainerSIcDnqV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L4yMAbuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l4yMAbu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l4yMAbu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'role' => ['privates', '.errored..service_locator.l4yMAbu.App\\Entity\\Role', NULL, 'Cannot autowire service ".service_locator.l4yMAbu": it needs an instance of "App\\Entity\\Role" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'role' => 'App\\Entity\\Role',
            'entityManager' => '?',
        ]);
    }
}
