<?php

namespace ContainerSIcDnqV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TDmwDGi.App\Controller\AuditController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TDmwDGi.App\\Controller\\AuditController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'audit' => ['privates', '.errored..service_locator.TDmwDGi.App\\Entity\\Audit', NULL, 'Cannot autowire service ".service_locator.TDmwDGi": it needs an instance of "App\\Entity\\Audit" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'audit' => 'App\\Entity\\Audit',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\AuditController::edit()', $container);
    }
}
