<?php

namespace ContainerANsONX4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QBh2uyKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qBh2uyK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qBh2uyK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'institution' => ['privates', '.errored..service_locator.qBh2uyK.App\\Entity\\Institution', NULL, 'Cannot autowire service ".service_locator.qBh2uyK": it needs an instance of "App\\Entity\\Institution" but this type has been excluded in "config/services.yaml".'],
        ], [
            'institution' => 'App\\Entity\\Institution',
        ]);
    }
}
