<?php

namespace ContainerANsONX4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AGatCqTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AGatCqT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AGatCqT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employeRepository' => ['privates', '.errored.ufebgri', NULL, 'Cannot determine controller argument for "App\\Controller\\DashboardController::adminDashboard()": the $employeRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\EmployeRepository". Did you forget to add a use statement?'],
            'congesRepository' => ['privates', '.errored.tc0cGeI', NULL, 'Cannot determine controller argument for "App\\Controller\\DashboardController::adminDashboard()": the $congesRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\CongesRepository". Did you forget to add a use statement?'],
            'pointageRepository' => ['privates', '.errored.rCOcSXx', NULL, 'Cannot determine controller argument for "App\\Controller\\DashboardController::adminDashboard()": the $pointageRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\PointageRepository". Did you forget to add a use statement?'],
        ], [
            'employeRepository' => '?',
            'congesRepository' => '?',
            'pointageRepository' => '?',
        ]);
    }
}
