<?php

namespace ContainerQctP8eZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDecaissementControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l5xpj_O.App\Controller\DecaissementController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l5xpj_O.App\\Controller\\DecaissementController::new()'] = ($container->privates['.service_locator.l5xpj_O'] ?? $container->load('get_ServiceLocator_L5xpjOService'))->withContext('App\\Controller\\DecaissementController::new()', $container);
    }
}
