<?php

namespace ContainerQctP8eZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerapiListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bTA9FKH.App\Controller\UserController::apiList()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bTA9FKH.App\\Controller\\UserController::apiList()'] = ($container->privates['.service_locator.bTA9FKH'] ?? $container->load('get_ServiceLocator_BTA9FKHService'))->withContext('App\\Controller\\UserController::apiList()', $container);
    }
}
