<?php

namespace ContainerAaVLWkb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2oscVQ4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2oscVQ4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2oscVQ4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'roleRepository' => ['privates', '.errored.REyH2XG', NULL, 'Cannot determine controller argument for "App\\Controller\\WebController::roles()": the $roleRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\RoleRepository". Did you forget to add a use statement?'],
        ], [
            'roleRepository' => '?',
        ]);
    }
}
