<?php

namespace ContainerAaVLWkb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArrayAdapterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Omines\DataTablesBundle\Adapter\ArrayAdapter' autowired service.
     *
     * @return \Omines\DataTablesBundle\Adapter\ArrayAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/omines/datatables-bundle/src/Adapter/AdapterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/omines/datatables-bundle/src/Adapter/ArrayAdapter.php';

        $container->factories['service_container']['Omines\\DataTablesBundle\\Adapter\\ArrayAdapter'] = function ($container) {
            return new \Omines\DataTablesBundle\Adapter\ArrayAdapter();
        };

        return $container->factories['service_container']['Omines\\DataTablesBundle\\Adapter\\ArrayAdapter']($container);
    }
}
