<?php

namespace ContainerAaVLWkb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gfm9iFm.App\Controller\AuditController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gfm9iFm.App\\Controller\\AuditController::show()'] = ($container->privates['.service_locator.Gfm9iFm'] ?? $container->load('get_ServiceLocator_Gfm9iFmService'))->withContext('App\\Controller\\AuditController::show()', $container);
    }
}
