<?php

namespace ContainerAaVLWkb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConventionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ConventionController' shared autowired service.
     *
     * @return \App\Controller\ConventionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ConventionController.php';

        $container->services['App\\Controller\\ConventionController'] = $instance = new \App\Controller\ConventionController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\ConventionRepository'] ?? $container->load('getConventionRepositoryService')), ($container->privates['App\\Repository\\FinancementRepository'] ?? $container->load('getFinancementRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\ConventionController', $container));

        return $instance;
    }
}
