<?php

namespace ContainerAaVLWkb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvExporterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Omines\DataTablesBundle\Exporter\Csv\CsvExporter' shared autowired service.
     *
     * @return \Omines\DataTablesBundle\Exporter\Csv\CsvExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/omines/datatables-bundle/src/Exporter/DataTableExporterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/omines/datatables-bundle/src/Exporter/Csv/CsvExporter.php';

        return $container->privates['Omines\\DataTablesBundle\\Exporter\\Csv\\CsvExporter'] = new \Omines\DataTablesBundle\Exporter\Csv\CsvExporter();
    }
}
