<?php

namespace ContainerAaVLWkb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDecaissementControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xCwkd1E.App\Controller\DecaissementController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xCwkd1E.App\\Controller\\DecaissementController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'decaissement' => ['privates', '.errored..service_locator.xCwkd1E.App\\Entity\\Decaissement', NULL, 'Cannot autowire service ".service_locator.xCwkd1E": it needs an instance of "App\\Entity\\Decaissement" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'decaissement' => 'App\\Entity\\Decaissement',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\DecaissementController::edit()', $container);
    }
}
