<?php

namespace ContainerLlV8w9s;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Tc0cGeIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.tc0cGeI' shared service.
     *
     * @return \App\Controller\CongesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\DashboardController::adminDashboard()": the $congesRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\CongesRepository". Did you forget to add a use statement?');
    }
}
