<?php

namespace ContainerLlV8w9s;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitutionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qBh2uyK.App\Entity\Institution' shared service.
     *
     * @return \App\Entity\Institution
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qBh2uyK": it needs an instance of "App\\Entity\\Institution" but this type has been excluded in "config/services.yaml".');
    }
}
