<?php

namespace ContainerUYBhCYa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_REyH2XGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.REyH2XG' shared service.
     *
     * @return \App\Controller\RoleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\WebController::roles()": the $roleRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\RoleRepository". Did you forget to add a use statement?');
    }
}
