<?php

namespace ContainerUYBhCYa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDataTableFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Omines\DataTablesBundle\DataTableFactory' shared autowired service.
     *
     * @return \Omines\DataTablesBundle\DataTableFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DataTableFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DataTableRendererInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'TwigRenderer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'Instantiator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Exporter'.\DIRECTORY_SEPARATOR.'DataTableExporterManager.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Exporter'.\DIRECTORY_SEPARATOR.'DataTableExporterCollection.php';

        return $container->services['Omines\\DataTablesBundle\\DataTableFactory'] = new \Omines\DataTablesBundle\DataTableFactory($container->parameters['datatables.config'], new \Omines\DataTablesBundle\Twig\TwigRenderer(($container->privates['twig'] ?? $container->load('getTwigService'))), new \Omines\DataTablesBundle\DependencyInjection\Instantiator(['Omines\\DataTablesBundle\\Adapter\\AdapterInterface' => new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Omines\\DataTablesBundle\\Adapter\\ArrayAdapter' => [false, 'Omines\\DataTablesBundle\\Adapter\\ArrayAdapter', 'getArrayAdapterService', true],
            'Omines\\DataTablesBundle\\Adapter\\Doctrine\\ORMAdapter' => [false, 'Omines\\DataTablesBundle\\Adapter\\Doctrine\\ORMAdapter', 'getORMAdapterService', true],
            'Omines\\DataTablesBundle\\Adapter\\Doctrine\\FetchJoinORMAdapter' => [false, 'Omines\\DataTablesBundle\\Adapter\\Doctrine\\FetchJoinORMAdapter', 'getFetchJoinORMAdapterService', true],
        ], [
            'Omines\\DataTablesBundle\\Adapter\\ArrayAdapter' => '?',
            'Omines\\DataTablesBundle\\Adapter\\Doctrine\\ORMAdapter' => '?',
            'Omines\\DataTablesBundle\\Adapter\\Doctrine\\FetchJoinORMAdapter' => '?',
        ]), 'Omines\\DataTablesBundle\\Column\\AbstractColumn' => new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Omines\\DataTablesBundle\\Column\\TwigColumn' => [false, 'Omines\\DataTablesBundle\\Column\\TwigColumn', 'getTwigColumnService', true],
            'Omines\\DataTablesBundle\\Column\\TwigStringColumn' => [false, 'Omines\\DataTablesBundle\\Column\\TwigStringColumn', 'getTwigStringColumnService', true],
        ], [
            'Omines\\DataTablesBundle\\Column\\TwigColumn' => '?',
            'Omines\\DataTablesBundle\\Column\\TwigStringColumn' => '?',
        ]), 'Omines\\DataTablesBundle\\DataTableTypeInterface' => new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], []), 'Omines\\DataTablesBundle\\Exporter\\DataTableExporterInterface' => new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelExporter' => ['privates', 'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelExporter', 'getExcelExporterService', true],
            'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelOpenSpoutExporter' => ['privates', 'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelOpenSpoutExporter', 'getExcelOpenSpoutExporterService', true],
            'Omines\\DataTablesBundle\\Exporter\\Csv\\CsvExporter' => ['privates', 'Omines\\DataTablesBundle\\Exporter\\Csv\\CsvExporter', 'getCsvExporterService', true],
        ], [
            'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelExporter' => '?',
            'Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelOpenSpoutExporter' => '?',
            'Omines\\DataTablesBundle\\Exporter\\Csv\\CsvExporter' => '?',
        ])]), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), new \Omines\DataTablesBundle\Exporter\DataTableExporterManager(new \Omines\DataTablesBundle\Exporter\DataTableExporterCollection(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelExporter'] ??= new \Omines\DataTablesBundle\Exporter\Excel\ExcelExporter());
            yield 1 => ($container->privates['Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelOpenSpoutExporter'] ??= new \Omines\DataTablesBundle\Exporter\Excel\ExcelOpenSpoutExporter());
            yield 2 => ($container->privates['Omines\\DataTablesBundle\\Exporter\\Csv\\CsvExporter'] ??= new \Omines\DataTablesBundle\Exporter\Csv\CsvExporter());
        }, 3)), ($container->services['translator'] ?? self::getTranslatorService($container))));
    }
}
