<?php

namespace ContainerUYBhCYa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixEmployeMigrationCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\FixEmployeMigrationCommand' shared autowired service.
     *
     * @return \App\Command\FixEmployeMigrationCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'FixEmployeMigrationCommand.php';

        $container->privates['App\\Command\\FixEmployeMigrationCommand'] = $instance = new \App\Command\FixEmployeMigrationCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));

        $instance->setName('app:fix-employe-migration');
        $instance->setDescription('Corrige les problèmes de migration pour la relation Employe-User');

        return $instance;
    }
}
