<?php

namespace ContainerUYBhCYa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitutionControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qBh2uyK.App\Controller\InstitutionController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qBh2uyK.App\\Controller\\InstitutionController::delete()'] = ($container->privates['.service_locator.qBh2uyK'] ?? $container->load('get_ServiceLocator_QBh2uyKService'))->withContext('App\\Controller\\InstitutionController::delete()', $container);
    }
}
