<?php

namespace ContainerUYBhCYa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStimulus_HelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'stimulus.helper' shared service.
     *
     * @return \Symfony\UX\StimulusBundle\Helper\StimulusHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'stimulus-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Helper'.\DIRECTORY_SEPARATOR.'StimulusHelper.php';

        $a = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->privates['stimulus.helper'])) {
            return $container->privates['stimulus.helper'];
        }

        return $container->privates['stimulus.helper'] = new \Symfony\UX\StimulusBundle\Helper\StimulusHelper($a);
    }
}
