<?php

namespace Container3jihos0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gfm9iFmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gfm9iFm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gfm9iFm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'audit' => ['privates', '.errored..service_locator.Gfm9iFm.App\\Entity\\Audit', NULL, 'Cannot autowire service ".service_locator.Gfm9iFm": it needs an instance of "App\\Entity\\Audit" but this type has been excluded in "config/services.yaml".'],
        ], [
            'audit' => 'App\\Entity\\Audit',
        ]);
    }
}
