<?php

namespace Container3jihos0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qaRzevw.App\Controller\ActivityController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qaRzevw.App\\Controller\\ActivityController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activity' => ['privates', '.errored..service_locator.qaRzevw.App\\Entity\\UserActivity', NULL, 'Cannot autowire service ".service_locator.qaRzevw": it needs an instance of "App\\Entity\\UserActivity" but this type has been excluded in "config/services.yaml".'],
        ], [
            'activity' => 'App\\Entity\\UserActivity',
        ]))->withContext('App\\Controller\\ActivityController::show()', $container);
    }
}
