<?php

namespace Container3jihos0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ActivityController' shared autowired service.
     *
     * @return \App\Controller\ActivityController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ActivityController.php';

        $container->services['App\\Controller\\ActivityController'] = $instance = new \App\Controller\ActivityController(($container->privates['App\\Repository\\UserActivityRepository'] ?? $container->load('getUserActivityRepositoryService')), ($container->services['App\\Service\\ActivityLogger'] ?? self::getActivityLoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\ActivityController', $container));

        return $instance;
    }
}
