<?php

namespace Container3jihos0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConventionControllercancelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lvJ9LeN.App\Controller\ConventionController::cancel()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lvJ9LeN.App\\Controller\\ConventionController::cancel()'] = ($container->privates['.service_locator.lvJ9LeN'] ?? $container->load('get_ServiceLocator_LvJ9LeNService'))->withContext('App\\Controller\\ConventionController::cancel()', $container);
    }
}
