<?php

namespace Container3jihos0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartnerControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cvAK_XJ.App\Controller\PartnerController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cvAK_XJ.App\\Controller\\PartnerController::edit()'] = ($container->privates['.service_locator.cvAK_XJ'] ?? $container->load('get_ServiceLocator_CvAKXJService'))->withContext('App\\Controller\\PartnerController::edit()', $container);
    }
}
