<?php

namespace Container3jihos0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwigColumnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Omines\DataTablesBundle\Column\TwigColumn' autowired service.
     *
     * @return \Omines\DataTablesBundle\Column\TwigColumn
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Column'.\DIRECTORY_SEPARATOR.'AbstractColumn.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Column'.\DIRECTORY_SEPARATOR.'TwigColumn.php';

        $container->factories['service_container']['Omines\\DataTablesBundle\\Column\\TwigColumn'] = function ($container) {
            return new \Omines\DataTablesBundle\Column\TwigColumn(($container->privates['twig'] ?? $container->load('getTwigService')));
        };

        return $container->factories['service_container']['Omines\\DataTablesBundle\\Column\\TwigColumn']($container);
    }
}
