<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDAXrtXc\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDAXrtXc/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDAXrtXc.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDAXrtXc\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDAXrtXc\App_KernelProdContainer([
    'container.build_hash' => 'DAXrtXc',
    'container.build_id' => '08168d58',
    'container.build_time' => 1764696044,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDAXrtXc');
