<?php

namespace Container6PGPPOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LvJ9LeNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lvJ9LeN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lvJ9LeN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'convention' => ['privates', '.errored..service_locator.lvJ9LeN.App\\Entity\\Convention', NULL, 'Cannot autowire service ".service_locator.lvJ9LeN": it needs an instance of "App\\Entity\\Convention" but this type has been excluded in "config/services.yaml".'],
        ], [
            'convention' => 'App\\Entity\\Convention',
        ]);
    }
}
