<?php

namespace Container6PGPPOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KjAHTcjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kjAHTcj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kjAHTcj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loginHistoryRepository' => ['privates', '.errored.mU_kUNL', NULL, 'Cannot determine controller argument for "App\\Controller\\WebController::loginHistory()": the $loginHistoryRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\LoginHistoryRepository". Did you forget to add a use statement?'],
        ], [
            'loginHistoryRepository' => '?',
        ]);
    }
}
