<?php

namespace Container6PGPPOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAudit2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TDmwDGi.App\Entity\Audit' shared service.
     *
     * @return \App\Entity\Audit
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.TDmwDGi": it needs an instance of "App\\Entity\\Audit" but this type has been excluded in "config/services.yaml".');
    }
}
