<?php

namespace Container6PGPPOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvExporterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Omines\DataTablesBundle\Exporter\Csv\CsvExporter' shared autowired service.
     *
     * @return \Omines\DataTablesBundle\Exporter\Csv\CsvExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Exporter'.\DIRECTORY_SEPARATOR.'DataTableExporterInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Exporter'.\DIRECTORY_SEPARATOR.'Csv'.\DIRECTORY_SEPARATOR.'CsvExporter.php';

        return $container->privates['Omines\\DataTablesBundle\\Exporter\\Csv\\CsvExporter'] = new \Omines\DataTablesBundle\Exporter\Csv\CsvExporter();
    }
}
