<?php

namespace Container6PGPPOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixUserInstitutionCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\FixUserInstitutionCommand' shared autowired service.
     *
     * @return \App\Command\FixUserInstitutionCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'FixUserInstitutionCommand.php';

        $container->privates['App\\Command\\FixUserInstitutionCommand'] = $instance = new \App\Command\FixUserInstitutionCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:fix-user-institution');
        $instance->setDescription('Corrige et vérifie les relations User-Institution et User-Employe');

        return $instance;
    }
}
