<?php

namespace Container6PGPPOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Runtime_BlurHashService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'twig.runtime.blur_hash' shared service.
     *
     * @return \Symfony\UX\LazyImage\Twig\BlurHashRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-lazy-image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'BlurHashRuntime.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-lazy-image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'BlurHash'.\DIRECTORY_SEPARATOR.'BlurHashInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-lazy-image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'BlurHash'.\DIRECTORY_SEPARATOR.'BlurHash.php';

        return $container->privates['twig.runtime.blur_hash'] = new \Symfony\UX\LazyImage\Twig\BlurHashRuntime(new \Symfony\UX\LazyImage\BlurHash\BlurHash(NULL, NULL, NULL));
    }
}
