<?php

namespace ContainerOeWmASj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConvention2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lvJ9LeN.App\Entity\Convention' shared service.
     *
     * @return \App\Entity\Convention
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lvJ9LeN": it needs an instance of "App\\Entity\\Convention" but this type has been excluded in "config/services.yaml".');
    }
}
