<?php

namespace ContainerOeWmASj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanupActivitiesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CleanupActivitiesCommand' shared autowired service.
     *
     * @return \App\Command\CleanupActivitiesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CleanupActivitiesCommand.php';

        $container->privates['App\\Command\\CleanupActivitiesCommand'] = $instance = new \App\Command\CleanupActivitiesCommand(($container->services['App\\Service\\ActivityLogger'] ?? self::getActivityLoggerService($container)));

        $instance->setName('app:activities:cleanup');
        $instance->setDescription('Nettoie les anciennes activités de la base de données');

        return $instance;
    }
}
