<?php

namespace ContainerOeWmASj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDecaissementControllervalidateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IaeFFLq.App\Controller\DecaissementController::validate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IaeFFLq.App\\Controller\\DecaissementController::validate()'] = ($container->privates['.service_locator.IaeFFLq'] ?? $container->load('get_ServiceLocator_IaeFFLqService'))->withContext('App\\Controller\\DecaissementController::validate()', $container);
    }
}
