<?php

namespace ContainerOeWmASj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleControllertoggleStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pVdAH_Q.App\Controller\RoleController::toggleStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pVdAH_Q.App\\Controller\\RoleController::toggleStatus()'] = ($container->privates['.service_locator.pVdAH_Q'] ?? $container->load('get_ServiceLocator_PVdAHQService'))->withContext('App\\Controller\\RoleController::toggleStatus()', $container);
    }
}
