<?php

namespace ContainerOeWmASj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTopManagementControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TopManagementController' shared autowired service.
     *
     * @return \App\Controller\TopManagementController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'TopManagementController.php';

        $container->services['App\\Controller\\TopManagementController'] = $instance = new \App\Controller\TopManagementController(($container->privates['App\\Repository\\ProjectRepository'] ?? $container->load('getProjectRepositoryService')), ($container->privates['App\\Repository\\FinancementRepository'] ?? $container->load('getFinancementRepositoryService')), ($container->privates['App\\Repository\\DecaissementRepository'] ?? $container->load('getDecaissementRepositoryService')), ($container->privates['App\\Repository\\InstitutionRepository'] ?? $container->load('getInstitutionRepositoryService')), ($container->privates['App\\Repository\\AuditRepository'] ?? $container->load('getAuditRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\TopManagementController', $container));

        return $instance;
    }
}
