<?php

namespace ContainerUa3SGfL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcelExporterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Omines\DataTablesBundle\Exporter\Excel\ExcelExporter' shared autowired service.
     *
     * @return \Omines\DataTablesBundle\Exporter\Excel\ExcelExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Exporter'.\DIRECTORY_SEPARATOR.'DataTableExporterInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'omines'.\DIRECTORY_SEPARATOR.'datatables-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Exporter'.\DIRECTORY_SEPARATOR.'Excel'.\DIRECTORY_SEPARATOR.'ExcelExporter.php';

        return $container->privates['Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelExporter'] = new \Omines\DataTablesBundle\Exporter\Excel\ExcelExporter();
    }
}
