<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Project extends \App\Entity\Project implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'beneficiaires' => [parent::class, 'beneficiaires', null],
        "\0".parent::class."\0".'budgetTotal' => [parent::class, 'budgetTotal', null],
        "\0".parent::class."\0".'chefProjet' => [parent::class, 'chefProjet', null],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'dateDebut' => [parent::class, 'dateDebut', null],
        "\0".parent::class."\0".'dateFin' => [parent::class, 'dateFin', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'financementAutre' => [parent::class, 'financementAutre', null],
        "\0".parent::class."\0".'financementNational' => [parent::class, 'financementNational', null],
        "\0".parent::class."\0".'financementPartenaires' => [parent::class, 'financementPartenaires', null],
        "\0".parent::class."\0".'financements' => [parent::class, 'financements', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'institution' => [parent::class, 'institution', null],
        "\0".parent::class."\0".'localisation' => [parent::class, 'localisation', null],
        "\0".parent::class."\0".'maitreOuvrage' => [parent::class, 'maitreOuvrage', null],
        "\0".parent::class."\0".'montantDecaisse' => [parent::class, 'montantDecaisse', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null],
        "\0".parent::class."\0".'partnerPrincipal' => [parent::class, 'partnerPrincipal', null],
        "\0".parent::class."\0".'partners' => [parent::class, 'partners', null],
        "\0".parent::class."\0".'priorite' => [parent::class, 'priorite', null],
        "\0".parent::class."\0".'progress' => [parent::class, 'progress', null],
        "\0".parent::class."\0".'sector' => [parent::class, 'sector', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'sourceFinancement' => [parent::class, 'sourceFinancement', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'beneficiaires' => [parent::class, 'beneficiaires', null],
        'budgetTotal' => [parent::class, 'budgetTotal', null],
        'chefProjet' => [parent::class, 'chefProjet', null],
        'code' => [parent::class, 'code', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'dateDebut' => [parent::class, 'dateDebut', null],
        'dateFin' => [parent::class, 'dateFin', null],
        'description' => [parent::class, 'description', null],
        'financementAutre' => [parent::class, 'financementAutre', null],
        'financementNational' => [parent::class, 'financementNational', null],
        'financementPartenaires' => [parent::class, 'financementPartenaires', null],
        'financements' => [parent::class, 'financements', null],
        'id' => [parent::class, 'id', null],
        'institution' => [parent::class, 'institution', null],
        'localisation' => [parent::class, 'localisation', null],
        'maitreOuvrage' => [parent::class, 'maitreOuvrage', null],
        'montantDecaisse' => [parent::class, 'montantDecaisse', null],
        'name' => [parent::class, 'name', null],
        'notes' => [parent::class, 'notes', null],
        'partnerPrincipal' => [parent::class, 'partnerPrincipal', null],
        'partners' => [parent::class, 'partners', null],
        'priorite' => [parent::class, 'priorite', null],
        'progress' => [parent::class, 'progress', null],
        'sector' => [parent::class, 'sector', null],
        'slug' => [parent::class, 'slug', null],
        'sourceFinancement' => [parent::class, 'sourceFinancement', null],
        'status' => [parent::class, 'status', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
