<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Institution extends \App\Entity\Institution implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'acronym' => [parent::class, 'acronym', null],
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'creationDate' => [parent::class, 'creationDate', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'headName' => [parent::class, 'headName', null],
        "\0".parent::class."\0".'headTitle' => [parent::class, 'headTitle', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'logo' => [parent::class, 'logo', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'sector' => [parent::class, 'sector', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'typeInstitution' => [parent::class, 'typeInstitution', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null],
        "\0".parent::class."\0".'website' => [parent::class, 'website', null],
        'acronym' => [parent::class, 'acronym', null],
        'address' => [parent::class, 'address', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'creationDate' => [parent::class, 'creationDate', null],
        'description' => [parent::class, 'description', null],
        'email' => [parent::class, 'email', null],
        'headName' => [parent::class, 'headName', null],
        'headTitle' => [parent::class, 'headTitle', null],
        'id' => [parent::class, 'id', null],
        'logo' => [parent::class, 'logo', null],
        'name' => [parent::class, 'name', null],
        'phone' => [parent::class, 'phone', null],
        'sector' => [parent::class, 'sector', null],
        'slug' => [parent::class, 'slug', null],
        'status' => [parent::class, 'status', null],
        'typeInstitution' => [parent::class, 'typeInstitution', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'users' => [parent::class, 'users', null],
        'website' => [parent::class, 'website', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
