<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Financement extends \App\Entity\Financement implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bailleur' => [parent::class, 'bailleur', null],
        "\0".parent::class."\0".'conditions' => [parent::class, 'conditions', null],
        "\0".parent::class."\0".'contrepartieNationale' => [parent::class, 'contrepartieNationale', null],
        "\0".parent::class."\0".'conventions' => [parent::class, 'conventions', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'dateEcheance' => [parent::class, 'dateEcheance', null],
        "\0".parent::class."\0".'dateEntreeVigueur' => [parent::class, 'dateEntreeVigueur', null],
        "\0".parent::class."\0".'dateSignature' => [parent::class, 'dateSignature', null],
        "\0".parent::class."\0".'decaissements' => [parent::class, 'decaissements', null],
        "\0".parent::class."\0".'differeRemboursement' => [parent::class, 'differeRemboursement', null],
        "\0".parent::class."\0".'dureeFinancement' => [parent::class, 'dureeFinancement', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'montantDecaisse' => [parent::class, 'montantDecaisse', null],
        "\0".parent::class."\0".'montantEngage' => [parent::class, 'montantEngage', null],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null],
        "\0".parent::class."\0".'numeroConvention' => [parent::class, 'numeroConvention', null],
        "\0".parent::class."\0".'projets' => [parent::class, 'projets', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null],
        "\0".parent::class."\0".'tauxInteret' => [parent::class, 'tauxInteret', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'bailleur' => [parent::class, 'bailleur', null],
        'conditions' => [parent::class, 'conditions', null],
        'contrepartieNationale' => [parent::class, 'contrepartieNationale', null],
        'conventions' => [parent::class, 'conventions', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'dateEcheance' => [parent::class, 'dateEcheance', null],
        'dateEntreeVigueur' => [parent::class, 'dateEntreeVigueur', null],
        'dateSignature' => [parent::class, 'dateSignature', null],
        'decaissements' => [parent::class, 'decaissements', null],
        'differeRemboursement' => [parent::class, 'differeRemboursement', null],
        'dureeFinancement' => [parent::class, 'dureeFinancement', null],
        'id' => [parent::class, 'id', null],
        'montantDecaisse' => [parent::class, 'montantDecaisse', null],
        'montantEngage' => [parent::class, 'montantEngage', null],
        'notes' => [parent::class, 'notes', null],
        'numeroConvention' => [parent::class, 'numeroConvention', null],
        'projets' => [parent::class, 'projets', null],
        'slug' => [parent::class, 'slug', null],
        'statut' => [parent::class, 'statut', null],
        'tauxInteret' => [parent::class, 'tauxInteret', null],
        'type' => [parent::class, 'type', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
