<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Partner extends \App\Entity\Partner implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'acronym' => [parent::class, 'acronym', null],
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'contactEmail' => [parent::class, 'contactEmail', null],
        "\0".parent::class."\0".'contactName' => [parent::class, 'contactName', null],
        "\0".parent::class."\0".'contactPhone' => [parent::class, 'contactPhone', null],
        "\0".parent::class."\0".'contactRole' => [parent::class, 'contactRole', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'logo' => [parent::class, 'logo', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'projects' => [parent::class, 'projects', null],
        "\0".parent::class."\0".'siteWeb' => [parent::class, 'siteWeb', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'typePartner' => [parent::class, 'typePartner', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'acronym' => [parent::class, 'acronym', null],
        'address' => [parent::class, 'address', null],
        'contactEmail' => [parent::class, 'contactEmail', null],
        'contactName' => [parent::class, 'contactName', null],
        'contactPhone' => [parent::class, 'contactPhone', null],
        'contactRole' => [parent::class, 'contactRole', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'logo' => [parent::class, 'logo', null],
        'name' => [parent::class, 'name', null],
        'projects' => [parent::class, 'projects', null],
        'siteWeb' => [parent::class, 'siteWeb', null],
        'slug' => [parent::class, 'slug', null],
        'status' => [parent::class, 'status', null],
        'typePartner' => [parent::class, 'typePartner', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
