<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\DashboardController::adminDashboard' => ['privates', '.service_locator.AGatCqT', 'get_ServiceLocator_AGatCqTService', true],
            'App\\Controller\\RoleController::index' => ['privates', '.service_locator.2xhCPME.App\\Controller\\RoleController::index()', 'getRoleControllerindexService', true],
            'App\\Controller\\RoleController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\RoleController::new()', 'getRoleControllernewService', true],
            'App\\Controller\\RoleController::show' => ['privates', '.service_locator.pVdAH_Q.App\\Controller\\RoleController::show()', 'getRoleControllershowService', true],
            'App\\Controller\\RoleController::edit' => ['privates', '.service_locator.l4yMAbu.App\\Controller\\RoleController::edit()', 'getRoleControllereditService', true],
            'App\\Controller\\RoleController::delete' => ['privates', '.service_locator.l4yMAbu.App\\Controller\\RoleController::delete()', 'getRoleControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.8_gton2.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.__CzQUd.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.hKA2je_.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.Qh67eS1.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserController::toggleStatus' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::toggleStatus()', 'getUserControllertoggleStatusService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\DashboardController:adminDashboard' => ['privates', '.service_locator.AGatCqT', 'get_ServiceLocator_AGatCqTService', true],
            'App\\Controller\\RoleController:index' => ['privates', '.service_locator.2xhCPME.App\\Controller\\RoleController::index()', 'getRoleControllerindexService', true],
            'App\\Controller\\RoleController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\RoleController::new()', 'getRoleControllernewService', true],
            'App\\Controller\\RoleController:show' => ['privates', '.service_locator.pVdAH_Q.App\\Controller\\RoleController::show()', 'getRoleControllershowService', true],
            'App\\Controller\\RoleController:edit' => ['privates', '.service_locator.l4yMAbu.App\\Controller\\RoleController::edit()', 'getRoleControllereditService', true],
            'App\\Controller\\RoleController:delete' => ['privates', '.service_locator.l4yMAbu.App\\Controller\\RoleController::delete()', 'getRoleControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.8_gton2.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.__CzQUd.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.hKA2je_.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.Qh67eS1.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserController:toggleStatus' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::toggleStatus()', 'getUserControllertoggleStatusService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\DashboardController::adminDashboard' => '?',
            'App\\Controller\\RoleController::index' => '?',
            'App\\Controller\\RoleController::new' => '?',
            'App\\Controller\\RoleController::show' => '?',
            'App\\Controller\\RoleController::edit' => '?',
            'App\\Controller\\RoleController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::toggleStatus' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\DashboardController:adminDashboard' => '?',
            'App\\Controller\\RoleController:index' => '?',
            'App\\Controller\\RoleController:new' => '?',
            'App\\Controller\\RoleController:show' => '?',
            'App\\Controller\\RoleController:edit' => '?',
            'App\\Controller\\RoleController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:toggleStatus' => '?',
        ]));
    }
}
