<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcelOpenSpoutExporterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Omines\DataTablesBundle\Exporter\Excel\ExcelOpenSpoutExporter' shared autowired service.
     *
     * @return \Omines\DataTablesBundle\Exporter\Excel\ExcelOpenSpoutExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelOpenSpoutExporter'] = new \Omines\DataTablesBundle\Exporter\Excel\ExcelOpenSpoutExporter();
    }
}
