<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixEmployeMigrationCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\FixEmployeMigrationCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\FixEmployeMigrationCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:fix-employe-migration', [], 'Corrige les problèmes de migration pour la relation Employe-User', false, #[\Closure(name: 'App\\Command\\FixEmployeMigrationCommand')] fn (): \App\Command\FixEmployeMigrationCommand => ($container->privates['App\\Command\\FixEmployeMigrationCommand'] ?? $container->load('getFixEmployeMigrationCommandService')));
    }
}
