<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixEmployeMigrationCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\FixEmployeMigrationCommand' shared autowired service.
     *
     * @return \App\Command\FixEmployeMigrationCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\FixEmployeMigrationCommand'] = $instance = new \App\Command\FixEmployeMigrationCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));

        $instance->setName('app:fix-employe-migration');
        $instance->setDescription('Corrige les problèmes de migration pour la relation Employe-User');

        return $instance;
    }
}
