<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleControllereditService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.l4yMAbu.App\Controller\RoleController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.l4yMAbu'] ?? $container->load('get_ServiceLocator_L4yMAbuService'));

        if (isset($container->privates['.service_locator.l4yMAbu.App\\Controller\\RoleController::edit()'])) {
            return $container->privates['.service_locator.l4yMAbu.App\\Controller\\RoleController::edit()'];
        }

        return $container->privates['.service_locator.l4yMAbu.App\\Controller\\RoleController::edit()'] = $a->withContext('App\\Controller\\RoleController::edit()', $container);
    }
}
