<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStimulus_HelperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'stimulus.helper' shared service.
     *
     * @return \Symfony\UX\StimulusBundle\Helper\StimulusHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->privates['stimulus.helper'])) {
            return $container->privates['stimulus.helper'];
        }

        return $container->privates['stimulus.helper'] = new \Symfony\UX\StimulusBundle\Helper\StimulusHelper($a);
    }
}
