<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Runtime_BlurHashService extends App_KernelProdContainer
{
    /*
     * Gets the private 'twig.runtime.blur_hash' shared service.
     *
     * @return \Symfony\UX\LazyImage\Twig\BlurHashRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['twig.runtime.blur_hash'] = new \Symfony\UX\LazyImage\Twig\BlurHashRuntime(new \Symfony\UX\LazyImage\BlurHash\BlurHash(NULL, NULL, NULL));
    }
}
