<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_BatchActionControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'ux.live_component.batch_action_controller' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Controller\BatchActionController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['ux.live_component.batch_action_controller'] = new \Symfony\UX\LiveComponent\Controller\BatchActionController(($container->services['http_kernel'] ?? self::getHttpKernelService($container)));
    }
}
