<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_QueryStringInitializerSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the private 'ux.live_component.query_string_initializer_subscriber' shared service.
     *
     * @return \Symfony\UX\LiveComponent\EventListener\QueryStringInitializeSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['ux.live_component.query_string_initializer_subscriber'] = new \Symfony\UX\LiveComponent\EventListener\QueryStringInitializeSubscriber(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['ux.live_component.metadata_factory'] ?? $container->load('getUx_LiveComponent_MetadataFactoryService')), new \Symfony\UX\LiveComponent\Util\QueryStringPropsExtractor(($container->privates['ux.live_component.component_hydrator'] ?? $container->load('getUx_LiveComponent_ComponentHydratorService'))), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)));
    }
}
