<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_LiveComponentStackService extends App_KernelProdContainer
{
    /*
     * Gets the private 'ux.twig_component.live_component_stack' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Util\LiveComponentStack
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['ux.twig_component.live_component_stack'] = new \Symfony\UX\LiveComponent\Util\LiveComponentStack(($container->privates['ux.twig_component.component_stack'] ??= new \Symfony\UX\TwigComponent\ComponentStack()));
    }
}
