<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\WebController' shared autowired service.
     *
     * @return \App\Controller\WebController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\WebController'] = $instance = new \App\Controller\WebController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\WebController', $container));

        return $instance;
    }
}
