<?php

namespace ContainerDAXrtXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebAuthentificatorAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\WebAuthentificatorAuthenticator' shared autowired service.
     *
     * @return \App\Security\WebAuthentificatorAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\WebAuthentificatorAuthenticator'] = new \App\Security\WebAuthentificatorAuthenticator(($container->services['router'] ?? self::getRouterService($container)));
    }
}
