<?php

namespace ContainerXDU8fDQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ProjectController' shared autowired service.
     *
     * @return \App\Controller\ProjectController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ProjectController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ProjectStatisticsService.php';

        $a = ($container->privates['App\\Repository\\ProjectRepository'] ?? $container->load('getProjectRepositoryService'));

        $container->services['App\\Controller\\ProjectController'] = $instance = new \App\Controller\ProjectController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), $a, ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)), new \App\Service\ProjectStatisticsService($a), ($container->privates['App\\Repository\\DecaissementRepository'] ?? $container->load('getDecaissementRepositoryService')), ($container->privates['App\\Repository\\ConventionRepository'] ?? $container->load('getConventionRepositoryService')), ($container->privates['App\\Repository\\AuditRepository'] ?? $container->load('getAuditRepositoryService')), ($container->privates['App\\Repository\\CallForTenderRepository'] ?? $container->load('getCallForTenderRepositoryService')), ($container->privates['App\\Repository\\ProjectImageRepository'] ?? $container->load('getProjectImageRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\ProjectController', $container));

        return $instance;
    }
}
