<?php

namespace ContainerL8xJxFF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDecaissementControllercancelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IaeFFLq.App\Controller\DecaissementController::cancel()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IaeFFLq.App\\Controller\\DecaissementController::cancel()'] = ($container->privates['.service_locator.IaeFFLq'] ?? $container->load('get_ServiceLocator_IaeFFLqService'))->withContext('App\\Controller\\DecaissementController::cancel()', $container);
    }
}
