<?php

namespace ContainerO5HgsQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConventionControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.As9g3jo.App\Controller\ConventionController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.As9g3jo.App\\Controller\\ConventionController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'convention' => ['privates', '.errored..service_locator.As9g3jo.App\\Entity\\Convention', NULL, 'Cannot autowire service ".service_locator.As9g3jo": it needs an instance of "App\\Entity\\Convention" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'convention' => 'App\\Entity\\Convention',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\ConventionController::edit()', $container);
    }
}
