<?php

namespace ContainerO5HgsQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixUserInstitutionCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\FixUserInstitutionCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\FixUserInstitutionCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:fix-user-institution', [], 'Corrige et vérifie les relations User-Institution et User-Employe', false, #[\Closure(name: 'App\\Command\\FixUserInstitutionCommand')] fn (): \App\Command\FixUserInstitutionCommand => ($container->privates['App\\Command\\FixUserInstitutionCommand'] ?? $container->load('getFixUserInstitutionCommandService')));
    }
}
