<?php

namespace ContainerO5HgsQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitutionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\InstitutionController' shared autowired service.
     *
     * @return \App\Controller\InstitutionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/InstitutionController.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        $container->services['App\\Controller\\InstitutionController'] = $instance = new \App\Controller\InstitutionController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\InstitutionRepository'] ?? $container->load('getInstitutionRepositoryService')), ($container->privates['App\\Repository\\TypeInstitutionRepository'] ?? $container->load('getTypeInstitutionRepositoryService')), ($container->privates['App\\Repository\\SectorInstitutionRepository'] ?? $container->load('getSectorInstitutionRepositoryService')), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('en')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\InstitutionController', $container));

        return $instance;
    }
}
