<?php

namespace ContainerO5HgsQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l4yMAbu.App\Controller\RoleController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l4yMAbu.App\\Controller\\RoleController::delete()'] = ($container->privates['.service_locator.l4yMAbu'] ?? $container->load('get_ServiceLocator_L4yMAbuService'))->withContext('App\\Controller\\RoleController::delete()', $container);
    }
}
