<?php

namespace ContainerO5HgsQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Runtime_BlurHashService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'twig.runtime.blur_hash' shared service.
     *
     * @return \Symfony\UX\LazyImage\Twig\BlurHashRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-lazy-image/src/Twig/BlurHashRuntime.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-lazy-image/src/BlurHash/BlurHashInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-lazy-image/src/BlurHash/BlurHash.php';

        return $container->privates['twig.runtime.blur_hash'] = new \Symfony\UX\LazyImage\Twig\BlurHashRuntime(new \Symfony\UX\LazyImage\BlurHash\BlurHash(NULL, NULL, NULL));
    }
}
