<?php

namespace Container1qrBKBY;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerloginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hw3R0tW.App\Controller\SecurityController::login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Hw3R0tW.App\\Controller\\SecurityController::login()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['privates', '.errored.Si2aZc6', NULL, 'Cannot determine controller argument for "App\\Controller\\SecurityController::login()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
        ], [
            'request' => '?',
            'authenticationUtils' => '?',
        ]))->withContext('App\\Controller\\SecurityController::login()', $container);
    }
}
