<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXDU8fDQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXDU8fDQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXDU8fDQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXDU8fDQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXDU8fDQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'XDU8fDQ',
    'container.build_id' => '49d2f555',
    'container.build_time' => 1772537166,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXDU8fDQ');
