<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAaVLWkb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAaVLWkb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAaVLWkb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAaVLWkb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAaVLWkb\App_KernelDevDebugContainer([
    'container.build_hash' => 'AaVLWkb',
    'container.build_id' => 'd65955a8',
    'container.build_time' => 1766443776,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAaVLWkb');
