<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQjYa1pl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQjYa1pl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQjYa1pl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQjYa1pl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQjYa1pl\App_KernelDevDebugContainer([
    'container.build_hash' => 'QjYa1pl',
    'container.build_id' => '0f3b489d',
    'container.build_time' => 1765964055,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQjYa1pl');
